language: java
jdk:
- oraclejdk8
before_install:
- export | grep SAUCE_
env:
  global:
  - BUILD_TAG=$TRAVIS_REPO_SLUG+$TRAVIS_BUILD_NUMBER
  - SAUCE_USERNAME=sauce_examples
addons:
  jwt:
    secure: S9owLvXDqlX4ZNO5rKlZi8nom/EfHVG9sHyh7ZZb+eiU1ee+qupAi3uQt3v6h4lCRxYZNml/2fBZOwDN0xgsFFZcQcU+xD1vq3B2XhVQjJqf7+LQAdXpjTGLIdEW+BrEof0j66CJ4xhP148vQIvEY9ZeQmjxM/RbOxMe8kvwJgcYgMKX6mNA3UBikFq8Fh1MhKozkoZtZYSNAt9jh/KWY/dGs4CkmE9K9r1eOX50QGz18PXAxnd9lBvmxMwzlrwF915xwpQz4vcZxGGzJQr4flBg679Ov1yHvz0vx5vghfHIcAlOZmABIXV15ETi/O1YA9JGG1KzHakloGAV40tDqYH4WWQvyD9H5PMN007u+jQjsgMb8k+lH4GRSdtEklJ6/utfuymVVVVdzskcBdxIXU0lQ1rRDAHVQpG4gn0PLGSs3WFMOlbrSqn14JBwj6tPmAp2+Y/YYmnHg4YCFjG2G03KzNYzsqW7dM+DGnru8R/1CIXoy16bnWvA/PXNAir03EODyOKwHZ53EeMvZ6305aRPdaEEaKfSV515WXZyRTKfWwaCTCSUPIpglSG41zj0lBzqETh+gq1VFYFPhOiSBpE8G7gJzl/hQO5e3pAn95cG8ZiEXaBcoBRtN01rd4y1Jy2dmEOD4nejvKWRLP4x62ngENmlbf7vnbyuDGyWtoo=
